# Generated by Django 5.0.8 on 2024-08-10 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodeid', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NodeModel',
            fields=[
                ('gateway_id', models.CharField(blank=True, max_length=200, primary_key=True, serialize=False)),
                ('data_field', models.JSONField(blank=True, null=True)),
                ('node_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='node_backend.node')),
            ],
        ),
    ]
