# Generated by Django 4.1.13 on 2024-08-05 07:09

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodeid', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NodeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_id', models.CharField(blank=True, max_length=200)),
                ('data', djongo.models.fields.JSONField(blank=True, default=dict)),
                ('node_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='node_backend.node')),
            ],
        ),
    ]
