# Generated by Django 5.0.7 on 2024-08-07 05:04

import django.db.models.deletion
import djongo.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_id', models.CharField(blank=True, max_length=200)),
                ('data', djongo.models.fields.JSONField(blank=True, default=dict)),
                ('node_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='node_backend.node', unique=True)),
            ],
        ),
    ]
